// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"car-rental-backend/config"
	"car-rental-backend/internal/handler"
	"car-rental-backend/internal/repository"
	"car-rental-backend/internal/service"
	"car-rental-backend/pkg/database"
	"car-rental-backend/pkg/jwt"
	"car-rental-backend/pkg/minio"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*App, error) {
	db, err := database.NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	minioClient, err := minio.NewMinioClient(cfg)
	if err != nil {
		return nil, err
	}
	jwtManager := jwt.NewJWTManager(cfg)
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository, jwtManager)
	authHandler := handler.NewAuthHandler(userService)
	mediaService := service.NewMediaService(minioClient)
	carRepository := repository.NewCarRepository(db)
	carService := service.NewCarService(mediaService, carRepository)
	carHandler := handler.NewCarHandler(carService)
	renterRepository := repository.NewRenterRepository(db)
	renterService := service.NewRenterService(renterRepository, mediaService)
	renterHandler := handler.NewRenterHandler(renterService)
	rentalTransactionRepository := repository.NewRentalTransactionRepository(db)
	rentalTransactionService := service.NewRentalTransactionService(rentalTransactionRepository, carRepository, renterRepository)
	rentalTransactionHandler := handler.NewRentalTransactionHandler(rentalTransactionService)
	app := NewApp(db, minioClient, jwtManager, authHandler, carHandler, renterHandler, rentalTransactionHandler)
	return app, nil
}
